package hub

import (
	"io/fs"
	"testing"
)

// webUIBuilt reports whether the admin single-page app has been built into the
// embedded webdist. The dist is generated by `make web`, not committed (only
// webdist/.gitkeep is tracked), so a bare `go test ./...` with no prior build
// embeds only that sentinel. The SPA-serving tests use this to skip in that case
// rather than fail with a confusing 404 — CI and the Dockerfile build the UI, so
// there the assets are present and the tests run for real.
//
// @return bool True when the embedded webdist holds built assets (not just .gitkeep).
//
// @testcase TestAdminSPAServed skips via skipIfWebUINotBuilt when the UI is unbuilt.
func webUIBuilt() bool {
	entries, err := fs.ReadDir(uiAssets(), ".")
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.Name() != ".gitkeep" {
			return true
		}
	}
	return false
}

// skipIfWebUINotBuilt skips a test when the admin web app has not been built into
// the embedded webdist, so serving the SPA would 404. It keeps `go test ./...`
// green in a checkout that has not run `make web`, without weakening CI (which
// builds the UI, so the guard passes and the test runs).
//
// @arg t The test to skip when the UI is absent.
//
// @testcase TestAdminSPAServed skips through this guard when the UI is unbuilt.
func skipIfWebUINotBuilt(t *testing.T) {
	t.Helper()
	if !webUIBuilt() {
		t.Skip("admin web app not built (run `make web`); skipping SPA-serving test")
	}
}
